const treasureCardData = {
    '覺醒的瞬間(冰岩)': {
        'baseAtk': 0,
        'atkPercentage': 0.35,
        'attributeDamage': 0.6,
        'critRate': 0,
        'critDamage': 0.75
    },
    '雪地飛馳(冰薄荷)': {
        'baseAtk': 0,
        'atkPercentage': 0.35,
        'attributeDamage': 0,
        'critRate': 0.45,
        'critDamage': 0.75,
    },
    '幸福的回憶(雪花糖球)': {
        'baseAtk': 0,
        'atkPercentage': 0,
        'attributeDamage': 0,
        'critRate': 0.25,
        'critDamage': 0,
    },
    '特製料理(羅勒青醬)': {
        'baseAtk': 0,
        'atkPercentage': 0,
        'attributeDamage': 0.75,
        'critRate': 0.40,
        'critDamage': 0,
    },
    '狂熱狙擊(哈拉帕辣椒)': {
        'baseAtk': 0,
        'atkPercentage': 0,
        'attributeDamage': 0.45,
        'critRate': 0.25,
        'critDamage': 0.60,
    },
    '被喚醒的回憶(紫玉甘藍)': {
        'baseAtk': 0,
        'atkPercentage': 0.35,
        'attributeDamage': 0.516,
        'critRate': 0,
        'critDamage': 0,
    },
    '穿透之光(檸檬皮)': {
        'baseAtk': 0,
        'atkPercentage': 0.35,
        'attributeDamage': 0,
        'critRate': 0,
        'critDamage': 0,
    },
    '努力的成果(奶油蘇打)': {
        'baseAtk': 0,
        'atkPercentage': 0.35,
        'attributeDamage': 0.30,
        'critRate': 0,
        'critDamage': 0,
    },
    '黃昏追擊戰(黑麥)': {
        'baseAtk': 0,
        'atkPercentage': 0.35,
        'attributeDamage': 0.416,
        'critRate': 0,
        'critDamage': 0,
    },
    '作戰開始(甜辣醬)': {
        'baseAtk': 0,
        'atkPercentage': 0.35,
        'attributeDamage': 0,
        'critRate': 0,
        'critDamage': 1.40,
    },
    '無法回頭的選擇(黑巧克力)': {
        'baseAtk': 0,
        'atkPercentage': 0.35,
        'attributeDamage': 0,
        'critRate': 0,
        'critDamage': 0.70,
    },
    '被遺忘的魔法書的秘密(魔法師)': {
        'baseAtk': 0,
        'atkPercentage': 0.35,
        'attributeDamage': 0,
        'critRate': 0.16,
        'critDamage': 0,
    },

};